Auth Service running on port 3001
BadRequestError: request aborted
    at IncomingMessage.onAborted (D:\Self_learning\Career\Back-end\Micro\deeptest\node_modules\raw-body\index.js:245:10)
    at IncomingMessage.emit (node:events:524:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:122:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)
    at abortIncoming (node:_http_server:809:9)
    at socketOnClose (node:_http_server:803:3)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
BadRequestError: request aborted
    at IncomingMessage.onAborted (D:\Self_learning\Career\Back-end\Micro\deeptest\node_modules\raw-body\index.js:245:10)
    at IncomingMessage.emit (node:events:524:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:122:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)
    at abortIncoming (node:_http_server:809:9)
    at socketOnClose (node:_http_server:803:3)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
BadRequestError: request aborted
    at IncomingMessage.onAborted (D:\Self_learning\Career\Back-end\Micro\deeptest\node_modules\raw-body\index.js:245:10)
    at IncomingMessage.emit (node:events:524:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:122:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)
    at abortIncoming (node:_http_server:809:9)
    at socketOnClose (node:_http_server:803:3)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
